### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by eorroot** [lmy98129/VLPD#1]
您好，是否方便提供下论文里的可视化方法

**Comment by lmy98129** [comment]
您好，
由于一台机器的硬盘损坏，相关文件已经丢失，我们在百度和谷歌网盘的文件夹里面标识了，包括一些早期的baseline权重。
PS：因为这台机器GPU显存较小，不支持训练VLPD完整模型，主要是baseline复现的实验，以及可视化等不太占显存的任务。

因为我们近期有其他研究工作需要开展，暂时没有太多时间重新写这套代码。

关于VLS的分割结果，我们找到了当时暂存在别的机器上的代码，可能会与最终的可视化效果有一定区别，供您参考。
其中，total_prob_map就是VLS方法生成的分割结果，ratio用来调整原图和分割结果叠加的透明度比值。
colors就是附加材料里面说的，按照CityScapes的默认颜色稍微调了一下，让人的对应颜色更突出一点。

关于Grad-CAM的可视化，我们是在CLIP的[self.conv2](https://github.com/lmy98129/VLPD/blob/main/net/backbone/resnet50_clip_vlpd.py#L219)上做的，代码未暂存。
如果我们事情比较多，可能会很久没回issue，建议您发邮件联系我们，回复的即时性会好一些。

刘孟寅

```
def visualize_pseudo_mask(
    total_prob_map:Dict[str, torch.Tensor], 
    ratio=0.6,
    save_root='', 
    ):
      
    colors = [
        # ground
        ( 70, 70, 70),
        # building
        (200,200,200),
        # tree
        (107,142, 35),
        # human
        (220, 20, 60),
        # car
        (  0,  0,142),
        # bus
        (  0, 60,100),
        # bicycle
        (255,165,  0),
        # truck
        (  0,  0, 70),
        # traffic sign
        (220,220,  0),
        # sky
        ( 70,130,180),
    ]
    colors = np.asarray(colors)

    for filepath, prob_map in tqdm(total_prob_map.items(), desc='visualizing pseudo masks'):
        image = Image.open(filepath)
        
        img_size = image.size    

        prob_map: torch.Tensor = F.interpolate(prob_map, size=img_size[::-1], mode='bilinear')

        prob_map = prob_map.squeeze(dim=0)
        C, H, W = prob_map.shape

        class_map = np.argmax(prob_map, axis=0)
        mask: np.ndarray = colors[class_map]
        mask = mask.astype(int)

        masked_img = ratio * np.array(image) + (1 - ratio) * mask
        masked_img = Image.fromarray(np.uint8(masked_img.astype(int)))

        save_path = os.path.join(save_root, os.path.basename(filepath))

        if not os.path.exists(save_root): os.mkdir(save_root)
        masked_img.save(save_path)
```

**Comment by eorroot** [comment]
> 您好， 由于一台机器的硬盘损坏，相关文件已经丢失，我们在百度和谷歌网盘的文件夹里面标识了，包括一些早期的baseline权重。 PS：因为这台机器GPU显存较小，不支持训练VLPD完整模型，主要是baseline复现的实验，以及可视化等不太占显存的任务。
> 
> 因为我们近期有其他研究工作需要开展，暂时没有太多时间重新写这套代码。
> 
> 关于VLS的分割结果，我们找到了当时暂存在别的机器上的代码，可能会与最终的可视化效果有一定区别，供您参考。 其中，total_prob_map就是VLS方法生成的分割结果，ratio用来调整原图和分割结果叠加的透明度比值。 colors就是附加材料里面说的，按照CityScapes的默认颜色稍微调了一下，让人的对应颜色更突出一点。
> 
> 关于Grad-CAM的可视化，我们是在CLIP的[self.conv2](https://github.com/lmy98129/VLPD/blob/main/net/backbone/resnet50_clip_vlpd.py#L219)上做的，代码未暂存。 如果我们事情比较多，可能会很久没回issue，建议您发邮件联系我们，回复的即时性会好一些。
> 
> 刘孟寅
> 
> ```
> def visualize_pseudo_mask(
>     total_prob_map:Dict[str, torch.Tensor], 
>     ratio=0.6,
>     save_root='', 
>     ):
>       
>     colors = [
>         # ground
>         ( 70, 70, 70),
>         # building
>         (200,200,200),
>         # tree
>         (107,142, 35),
>         # human
>         (220, 20, 60),
>         # car
>         (  0,  0,142),
>         # bus
>         (  0, 60,100),
>         # bicycle
>         (255,165,  0),
>         # truck
>         (  0,  0, 70),
>         # traffic sign
>         (220,220,  0),
>         # sky
>         ( 70,130,180),
>     ]
>     colors = np.asarray(colors)
> 
>     for filepath, prob_map in tqdm(total_prob_map.items(), desc='visualizing pseudo masks'):
>         image = Image.open(filepath)
>         
>         img_size = image.size    
> 
>         prob_map: torch.Tensor = F.interpolate(prob_map, size=img_size[::-1], mode='bilinear')
> 
>         prob_map = prob_map.squeeze(dim=0)
>         C, H, W = prob_map.shape
> 
>         class_map = np.argmax(prob_map, axis=0)
>         mask: np.ndarray = colors[class_map]
>         mask = mask.astype(int)
> 
>         masked_img = ratio * np.array(image) + (1 - ratio) * mask
>         masked_img = Image.fromarray(np.uint8(masked_img.astype(int)))
> 
>         save_path = os.path.join(save_root, os.path.basename(filepath))
> 
>         if not os.path.exists(save_root): os.mkdir(save_root)
>         masked_img.save(save_path)
> ```

非常感谢您的帮助！根据您提供的代码，我已经预期的效果。
