### ISSUE TITLE
Error in loading model

### ISSUE THREAD

**Issue by YangJae96** [lmy98129/VLPD#3]
Thank you for your greak work.
I am getting error as shown in below.
***
Traceback (most recent call last):
  File "trainval_distributed.py", line 350, in <module>
    main()
  File "trainval_distributed.py", line 69, in main
    net = CSP(cfg).to(device)
  File "/root/workplace/detection/VLPD/net/detector.py", line 18, in __init__
    self.backbone = ResNet50_CLIP_VLPD(cfg)
  File "/root/workplace/detection/VLPD/net/backbone/resnet50_clip_vlpd.py", line 84, in __init__
    clip_model, preprocess = clip.load(name, tmp_device, jit, download_root)
  File "/root/anaconda3/envs/vlpd/lib/python3.8/site-packages/clip/clip.py", line 124, in load
    raise RuntimeError(f"Model {name} not found; available models = {available_models()}")
RuntimeError: Model /root/workplace/detection/VLPD/weight/clip_RN50.pt not found; available models = ['RN50', 'RN101', 'RN50x4', 'RN50x16', 'RN50x64', 'ViT-B/32', 'ViT-B/16', 'ViT-L/14', 'ViT-L/14@336px']
***

How should I properly load the clip model?

Looks like  argument 'name' in clip.load()  is defined by config.clip_weight.

1. Should I change the config file, clip_weight?
2. Then how do I upload the pretrained clip weights?

**Comment by lmy98129** [comment]
Hello, 

We have provided the detailed steps of using CLIP weights in "README.md" (the main page of this repository). 

Please refer to the last two items of the "STEP 1", "4. install the PIP package of CLIP" of "README.md"  to download the CLIP weight and keep the weight path consistent with config file. 

For no error occurrence, please follow our instructions in "README.md". Please inform us for further problems or close this issue if this reply helps you. Thank you!

Mengyin Liu

**Comment by YangJae96** [comment]
Thank you. 
The issue has been solved!
