### ISSUE TITLE
Attribute error

### ISSUE THREAD

**Issue by Ash5830** [lmy98129/VLPD#5]
I have been trying to run make file which is triggering setup and facing the below error. Plz help

 File "C:\Users\popur\miniconda3\envs\Ashenv\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
    self.build_extensions()
  File "setup.py", line 107, in build_extensions
    customize_compiler_for_nvcc(self.compiler)
  File "setup.py", line 81, in customize_compiler_for_nvcc
    default_compiler_so = self.compiler_so
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
make: *** [all] Error 1

**Comment by lmy98129** [comment]
This issue is about the difference

**Comment by lmy98129** [comment]
This issue is about the platform difference, i.e., Windows (non-unix-based) and Linux (unix-based). 
Our code is implemented on Linux by default. Please refer to more instructions by google.
https://stackoverflow.com/questions/52550831/attributeerror-msvccompiler-object-has-no-attribute-compiler-so
