### ISSUE TITLE
local_rank

### ISSUE THREAD

**Issue by hat783** [lmy98129/VLPD#6]
when trying to run dist_train.sh, i see a error related to --local_rank in trianval_distributed.py

usage: trainval_distributed.py [-h] [--work-dir WORK_DIR] [--local_rank LOCAL_RANK]
trainval_distributed.py: error: unrecognized arguments: --local-rank=1
usage: trainval_distributed.py [-h] [--work-dir WORK_DIR] [--local_rank LOCAL_RANK]
trainval_distributed.py: error: unrecognized arguments: --local-rank=0
[2023-12-08 01:40:46,962] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 2) local_rank: 0 (pid: 53342) of binary: /home/ashitha/miniconda3/envs/Ashenv/bin/python

could you please help me in resolving

**Comment by lmy98129** [comment]
Please check the version of PyTorch you are using, if it is inconsistent (typically too high) with the 1.10.0+cu113 in our provided environment requirement in [environment.yaml](https://github.com/lmy98129/VLPD/blob/main/environment.yaml#L133), this issue will occur like SysCV/sam-hq#41

PS: Please follow the steps of instructions in [README.md](https://github.com/lmy98129/VLPD/blob/main/README.md) to setup the environment.
