### ISSUE TITLE
When I am using the pre-trained model VLPD-262.pth to test the Citypersons datasets, there is a problem in 'net.module.load_state_dict(checkpoint['model'])'

### ISSUE THREAD

**Issue by GZHU-DVL** [lmy98129/VLPD#8]
This is the problem ' Unexpected key(s) in state_dict: "backbone.visual.layer4.0.conv1.weight", "backbone.visual.layer4.0.bn1.weight", "backbone.visual.layer4.0.bn1.bias", "backbone.visual.layer4.0.bn1.running_mean", "backbone.visual.layer4.0.bn1.running_var", "backbone.visual.layer4.0.bn1.num_batches_tracked", "backbone.visual.layer4.0.conv2.weight", "backbone.visual.layer4.0.bn2.weight", "backbone.visual.layer4.0.bn2.bias", "backbone.visual.layer4.0.bn2.running_mean", "backbone.visual.layer4.0.bn2.running_var", "backbone.visual.layer4.0.bn2.num_batches_tracked", "backbone.visual.layer4.0.conv3.weight", "backbone.visual.layer4.0.bn3.weight", "backbone.visual.layer4.0.bn3.bias", "backbone.visual.layer4.0.bn3.running_mean", "backbone.visual.layer4.0.bn3.running_var", "backbone.visual.layer4.0.bn3.num_batches_tracked", "backbone.visual.layer4.0.downsample.0.weight", "backbone.visual.layer4.0.downsample.1.weight", "backbone.visual.layer4.0.downsample.1.bias", "backbone.visual.layer4.0.downsample.1.running_mean", "backbone.visual.layer4.0.downsample.1.running_var", "backbone.visual.layer4.0.downsample.1.num_batches_tracked", "backbone.visual.layer4.1.conv1.weight", "backbone.visual.layer4.1.bn1.weight", "backbone.visual.layer4.1.bn1.bias", "backbone.visual.layer4.1.bn1.running_mean", "backbone.visual.layer4.1.bn1.running_var", "backbone.visual.layer4.1.bn1.num_batches_tracked", "backbone.visual.layer4.1.conv2.weight", "backbone.visual.layer4.1.bn2.weight", "backbone.visual.layer4.1.bn2.bias", "backbone.visual.layer4.1.bn2.running_mean", "backbone.visual.layer4.1.bn2.running_var", "backbone.visual.layer4.1.bn2.num_batches_tracked", "backbone.visual.layer4.1.conv3.weight", "backbone.visual.layer4.1.bn3.weight", "backbone.visual.layer4.1.bn3.bias", "backbone.visual.layer4.1.bn3.running_mean", "backbone.visual.layer4.1.bn3.running_var", "backbone.visual.layer4.1.bn3.num_batches_tracked", "backbone.visual.layer4.2.conv1.weight", "backbone.visual.layer4.2.bn1.weight", "backbone.visual.layer4.2.bn1.bias", "backbone.visual.layer4.2.bn1.running_mean", "backbone.visual.layer4.2.bn1.running_var", "backbone.visual.layer4.2.bn1.num_batches_tracked", "backbone.visual.layer4.2.conv2.weight", "backbone.visual.layer4.2.bn2.weight", "backbone.visual.layer4.2.bn2.bias", "backbone.visual.layer4.2.bn2.running_mean", "backbone.visual.layer4.2.bn2.running_var", "backbone.visual.layer4.2.bn2.num_batches_tracked", "backbone.visual.layer4.2.conv3.weight", "backbone.visual.layer4.2.bn3.weight", "backbone.visual.layer4.2.bn3.bias", "backbone.visual.layer4.2.bn3.running_mean", "backbone.visual.layer4.2.bn3.running_var", "backbone.visual.layer4.2.bn3.num_batches_tracked", "backbone.visual.attnpool.positional_embedding", "backbone.visual.attnpool.k_proj.weight", "backbone.visual.attnpool.k_proj.bias", "backbone.visual.attnpool.q_proj.weight", "backbone.visual.attnpool.q_proj.bias", "backbone.visual.attnpool.v_proj.weight", "backbone.visual.attnpool.v_proj.bias", "backbone.visual.attnpool.c_proj.weight", "backbone.visual.attnpool.c_proj.bias".
', how can I solve this problem?

**Comment by lmy98129** [comment]
Hello, 

This is a typical error of PyTorch when loading the weights. Please print the keys() of ``checkpoint['model']`` in [test.py](https://github.com/lmy98129/VLPD/blob/main/test.py#L50), and check the differences from the errors above. Please inform us if there are any differences, which will help us to debug. Thank you!

Mengyin Liu

**Comment by lmy98129** [comment]
@GZHU-DVL 
After the communication by emails, we found the bug is raised by the differences between early and latest versions. In early versions, the "del" code in [resnet50_clip_vlpd.py](https://github.com/lmy98129/VLPD/blob/main/net/backbone/resnet50_clip_vlpd.py#L109) is not added, which leads to two copies of CLIP weights in GPU memory and saved weights. The weight file is saved based on early versions, while the latest version is not debugged after such changing. 
Thanks for your responses! We will provide correct the code as soon as possible. 

Mengyin Liu
