### ISSUE TITLE
:Unexpected key(s) in state_dict

### ISSUE THREAD

**Issue by YanYan77** [lmy98129/VLPD#9]
how to deal with this problem:Unexpected key(s) in state_dict: "backbone.visual.layer4.0.conv1.weight", "backbone.visual.layer4.0.bn1.weight", "backbone.visual.layer4.0.bn1.bias", "backbone.visual.layer4.0.bn1.running_mean"....

**Comment by lmy98129** [comment]
Please see the solved issue #8. 
We have fixed the two lines of codes to remove the unexpected key del. 
Sorry for not fixing this bug in time.

Mengyin Liu

**Comment by YanYan77** [comment]
非常感谢您的回复，问题已经得到解决。但是很抱歉我又遇到了新的无法解决的问题。我想问一下这个问题如何解决
Traceback ( most recent call last ):
&nbsp;File " test . py ", line 163, in < module &gt;
&nbsp;main ()
&nbsp;File " test . py ", line 58, in main&nbsp;
&nbsp;val _ city ( testloader , net , cfg , args ) File " test . py ", line 79, in val _ city pos , height , offset = net ( inputs )
&nbsp;ValueErro ]: too many values to unpack ( expected 3)

------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lmy98129/VLPD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月20日(星期六) 下午2:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lmy98129/VLPD] :Unexpected key(s) in state_dict (Issue #9)





 
Please see the solved issue #8.
 We have fixed the two lines of codes to remove the unexpected key del.
 Sorry for not fixing this bug in time.
 
Mengyin Liu

**Comment by lmy98129** [comment]
@YanYan77 
Please see our new commit 00df918. 
We fix this bug by keeping the same output style during online-model testing in [trainval_distributed.py](https://github.com/lmy98129/VLPD/blob/main/trainval_distributed.py) and single-file testing in [test.py](https://github.com/lmy98129/VLPD/blob/main/test.py) on CityPersons, while other datasets have already been kept the same. 

Mengyin Liu

**Comment by YanYan77** [comment]
您好，请问方便提供一下可视化方法吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lmy98129/VLPD"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月21日(星期天) 中午11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lmy98129/VLPD] :Unexpected key(s) in state_dict (Issue #9)





 
@YanYan77
 Please see our new commit 00df918.
 We fix this bug by keeping the same output style during online-model testing in trainval_distributed.py and single-file testing in test.py on CityPersons, while other datasets have already been kept the same.
 
Mengyin Liu

**Comment by lmy98129** [comment]
Please read issue #1
